name: Publish to Winget

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        id: extract_version
        run: |
          version=$(echo "${{ github.event.release.tag_name }}" | sed "s/^sed-//")
          echo "version=$version" >> $GITHUB_OUTPUT
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: mbuilov.sed
          version: ${{ steps.extract_version.outputs.version }}
          installers-regex: 'sed-([\d.]+)-(x86|x64)\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
